name: cws Tests

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libssl-dev

  autobahn:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Autobahn Server
        run: pwd
        run: |
          sudo WITH_COMPRESSION=1 NO_DEBUG=1 make autobahn
      - name: Start Server
        run: |
          ./server & 
           echo "Starting..." &&
           sleep 5

      - name: Run Autobahn Test Suite
        run: |
          cd ./test/autobahn && sudo docker run --rm \
          -v "${PWD}/config:/config"  -v "${PWD}/reports:/reports" \
          --network="host"     \
          --name fuzzingclient \
          crossbario/autobahn-testsuite \
          wstest -m fuzzingclient --spec /config/fuzzingclient.json && cd ../../ && \
          python3 ./test/autobahn/report.py "test/autobahn/reports/servers/index.json" "cws"

  test-suite:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Suite
      run: sh tests.sh
